# Reset insomnia even in daytime
reset-in-daytime: true

# Require permission bedreset.use ?
use-permission: false

# Only allow one reset per night (resets automatically at morning)
once-per-night: true

# Send actionbar when insomnia is reset
send-actionbar: true
actionbar-message-rested: "&aYou feel rested."
actionbar-message-failed: "&cYou're not tired."